name: Anomaly.Org.Ua deployment 
on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout changes
    - uses: actions/checkout@v2
    - name: Build
    - uses: actions/setup-node@v1     
      with:
        node-version: 14.17.5
    - run: npm ci
    - run: npm run build:stage

    - name: SFTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
		local-dir: ./build
		